(() => {
'use strict';
const H=window.HANDBOOK,L=window.LEARNING,G=window.GAME_DATA,$=s=>document.querySelector(s),main=$('#main'),icons=window.UI_ICONS;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='vndirect-onboarding-0.5';let saved={};
try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
const object=x=>x&&typeof x==='object'&&!Array.isArray(x);
if(!object(saved))saved={};
const state={done:{},seen:{},answers:{},notes:{},last:'',...saved};
for(const k of ['done','seen','answers','notes'])if(!object(state[k]))state[k]={};
state.game=object(state.game)?state.game:{};
const game=state.game;
for(const k of ['mastered','drafts','evidence'])if(!object(game[k]))game[k]={};
if(!Array.isArray(game.awards))game.awards=[];
if(!object(game.profile)||typeof game.profile.name!=='string')game.profile=null;
if(game.profile){game.profile.name=game.profile.name.trim().slice(0,32);game.profile.avatar=game.profile.avatar==='female'?'female':'male';if(!game.profile.name)game.profile=null}
for(const [id,a]of Object.entries(state.answers))if(/^c[0-3]-\d+$/.test(id)&&a?.correct)game.mastered[id]=true;
const lessons=H.chapters.flatMap(c=>c.lessons.map(l=>({...l,chapter:c.id})));
const getLesson=id=>lessons.find(l=>l.id===id),getChapter=id=>H.chapters.find(c=>c.id===id);
let route='',trail=[],backing=false,toastTimer;
const persist=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}};
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3500)}
function to(path){if(location.hash.slice(1)===path)render();else location.hash=path}
const readRules=()=>Array.isArray(state.seen.ruleGuide)?state.seen.ruleGuide.filter(x=>(x>=227&&x<=233)||(x>=235&&x<=241)):[];
const checksDone=c=>c.id==='c4'?L.scenarios.every(s=>game.mastered[s.id]):L.checkpoints[c.id].every((_,i)=>game.mastered[c.id+'-'+i]);
const readDone=c=>c.id==='c4'?new Set(readRules()).size===14:c.lessons.every(l=>state.done[l.id]);
function doneChapter(c){return readDone(c)&&game.mastered['mission-'+c.id]&&checksDone(c)}
const completed=()=>H.chapters.filter(doneChapter).length;
const xp=()=>lessons.filter(l=>l.id!=='rules'&&state.done[l.id]).length*20+Object.keys(L.checkpoints).reduce((sum,c)=>sum+L.checkpoints[c].filter((_,i)=>game.mastered[c+'-'+i]).length*25,0)+H.chapters.filter(c=>game.mastered['mission-'+c.id]).length*80+L.scenarios.filter(s=>game.mastered[s.id]).length*40+new Set(readRules()).size*5+H.chapters.filter(c=>game.awards.includes(c.id)).length*100;
function settle(message){const fresh=H.chapters.filter(c=>doneChapter(c)&&!game.awards.includes(c.id));fresh.forEach(c=>game.awards.push(c.id));persist();if(fresh.length)window.HandbookUI.celebrate('Lên Level '+(completed()+1)+'!','+'+(fresh.length*100)+' XP · '+G.badges[H.chapters.indexOf(fresh[fresh.length-1])]);else if(message)window.HandbookUI.celebrate(message[0],message[1]);}
function master(id,points){if(game.mastered[id])return false;game.mastered[id]=true;persist();settle(['+'+points+' XP','Đã chinh phục thử thách. Tiếp tục nhé!']);return true}
const footer=()=>`<footer class="footer"><span>VNDIRECT · Phiên bản ${esc(H.version)} · Nội dung ${esc(H.date)}</span><span>Học để hiểu. Hiểu để hành nghề.</span></footer>`;
function crumbs(parts=[]){return `<nav class="crumbs" aria-label="Đường dẫn"><a href="#home">Trang chủ</a>${parts.map(p=>`<span aria-hidden="true">/</span>${p[1]?`<a href="#${p[1]}">${esc(p[0])}</a>`:`<span aria-current="page">${esc(p[0])}</span>`}`).join('')}<button data-back ${trail.length<2?'disabled':''}>← Trang vừa xem</button></nav>`}
const pagehead=(eyebrow,title,desc='')=>`<header class="pagehead"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1>${desc?`<p>${esc(desc)}</p>`:''}</header>`;
function objectives(c){return [
 {label:c.id==='c4'?"Khám phá DO & DON'T":'Đọc hồ sơ kiến thức',detail:c.id==='c4'?`${new Set(readRules()).size}/14 quy tắc`:`${c.lessons.filter(l=>state.done[l.id]).length}/${c.lessons.length} nội dung`,done:readDone(c),href:c.id==='c4'?'rules-guide/do/0':'lesson/'+(c.lessons.find(l=>!state.done[l.id])||c.lessons[0]).id+'/0'},
 {label:G.missions[c.id].title,detail:'+80 XP',done:!!game.mastered['mission-'+c.id],href:'mission/'+c.id},
 {label:c.id==='c4'?'Xử lý 7 hồ sơ tình huống':'Vượt trạm kiểm tra',detail:c.id==='c4'?`${L.scenarios.filter(s=>game.mastered[s.id]).length}/7 hồ sơ`:`${L.checkpoints[c.id].filter((_,i)=>game.mastered[c.id+'-'+i]).length}/${L.checkpoints[c.id].length} câu hỏi`,done:checksDone(c),href:c.id==='c4'?'rules/'+Math.max(0,L.scenarios.findIndex(s=>!game.mastered[s.id])):'check/'+c.id+'/'+Math.max(0,L.checkpoints[c.id].findIndex((_,i)=>!game.mastered[c.id+'-'+i]))}
]}
function nextAction(c){return objectives(c).find(o=>!o.done)?.href||'chapter/'+c.id}
const nextStage=()=>H.chapters.find(c=>!doneChapter(c));
function playerHUD(){const c=nextStage();return `<section class="player-hud" aria-label="Hồ sơ người chơi"><div class="hud-person">${window.playerAvatar(game.profile?.avatar)}<div><small>HỒ SƠ HÀNH TRÌNH</small><b>${esc(game.profile?.name||'Người học')}</b><button class="text-button" data-profile>Đổi nhân vật / tên</button></div></div><div class="hud-stat"><strong>Level ${completed()+1}</strong><span>${completed()}/5 chặng đã vượt</span></div><div class="hud-stat xp-stat"><strong>${xp()} <small>XP</small></strong><span>Điểm khám phá & thực hành</span></div><div class="hud-next"><span>${c?'Chặng kế tiếp':'Hoàn tất bản đồ 01'}</span><b>${esc(c?.label||'5 huy hiệu đã sưu tập')}</b><progress max="5" value="${completed()}" aria-label="Chặng hoàn thành"></progress></div></section>`}
function sidebar(path,chapter){const side=$('#sidebar');$('#layout').classList.toggle('with-side',!!path);side.hidden=!path;$('#menuToggle').hidden=!path;side.classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false');if(!path){side.innerHTML='';return}
 const link=(href,label,active,done=false)=>`<a href="#${href}" ${active?'aria-current="page"':''} class="${active?'active':''}"><span>${esc(label)}</span>${done?'<span class="nav-check" aria-label="Đã hoàn thành">✓</span>':''}${active?'<span class="current-dot" aria-hidden="true"></span>':''}</a>`;
 side.innerHTML=`<a class="side-map" href="#handbook">${icons.compass}<span>Bản đồ nghề nghiệp</span></a><div class="sidehead">05 CHẶNG · LEVEL ${completed()+1}</div>`+H.chapters.map((c,i)=>`<details ${chapter===c.id?'open':''}><summary class="${chapter===c.id?'in-path':''}"><span class="navnum">${String(i+1).padStart(2,'0')}</span><span>${esc(c.label)}</span>${doneChapter(c)?'<span class="nav-check" aria-label="Đã vượt chặng">✓</span>':''}</summary><div class="subnav">${link('chapter/'+c.id,'Nhiệm vụ của chặng',route==='chapter/'+c.id)}${c.id==='c4'?link('rules-guide/do/0',"Khám phá DO & DON'T",route.startsWith('rules-guide'))+link('summary','Tóm tắt quy tắc',route==='summary')+link('mission/c4','Phân loại quy tắc',route==='mission/c4',game.mastered['mission-c4'])+link('rules/0','Xử lý 7 tình huống',route.startsWith('rules/'),checksDone(c)):c.lessons.map(l=>link('lesson/'+l.id+'/0',l.title,route.startsWith('lesson/'+l.id+'/'),state.done[l.id])).join('')+link('mission/'+c.id,'Thử thách tương tác',route==='mission/'+c.id,game.mastered['mission-'+c.id])+link('check/'+c.id+'/0','Trạm kiểm tra',route.startsWith('check/'+c.id+'/'),checksDone(c))}</div></details>`).join('')+`<div class="side-progress"><b>${xp()} XP</b><small> · ${completed()}/5 huy hiệu</small><progress max="5" value="${completed()}" aria-label="Tiến độ bản đồ"></progress><p class="hint">Hoàn thành 3 nhiệm vụ của mỗi chặng để lên level. Bạn vẫn có thể tra cứu mọi nội dung.</p></div>`;
 if(route==='handbook')side.querySelector('.side-map').setAttribute('aria-current','page');
}
function profileForm(inDialog=false){const name=game.profile?.name||'',avatar=game.profile?.avatar||'male';return `<form class="profile-form" data-profile-form><p class="eyebrow">${name?'HỒ SƠ CỦA BẠN':'TẠO NHÂN VẬT'}</p><h2>${name?'Sẵn sàng cho chặng tiếp?':'Bạn là nhân vật chính.'}</h2><fieldset><legend>Chọn nhân viên đồng hành</legend><div class="avatar-options">${['male','female'].map(k=>`<label class="avatar-choice" data-tilt><input type="radio" name="avatar" value="${k}" ${avatar===k?'checked':''}>${window.playerAvatar(k)}<span>Nhân viên ${k==='male'?'nam':'nữ'}</span><i aria-hidden="true">✓</i></label>`).join('')}</div></fieldset><label class="name-label" for="${inDialog?'dialog':'home'}Name">Tên của bạn trong hành trình</label><input id="${inDialog?'dialog':'home'}Name" name="playerName" maxlength="32" required autocomplete="nickname" placeholder="Nhập tên bạn muốn dùng" value="${esc(name)}"><button class="primary" type="submit">${inDialog?'Lưu nhân vật':'Bắt đầu hành trình'} ${icons.arrow}</button><p class="hint">Bạn có thể đổi tên và nhân vật bất cứ lúc nào.</p></form>`}
function openProfile(){const d=$('#profileDialog');d.querySelector('.profile-body').innerHTML=profileForm(true);d.showModal();d.querySelector('[name=playerName]').focus()}
function home(){sidebar(null);document.title='VNDIRECT · Hành trình hội nhập';const next=nextStage();main.innerHTML=`<div class="home game-home"><section class="home-launch"><div class="home-intro"><p class="eyebrow"><span class="eyebrow-line"></span> VNDIRECT / HÀNH TRÌNH HỘI NHẬP</p><h1>Mỗi ngày học.<br><em>Một bước<br class="desktop-break"> vững nghề.</em></h1><p>Chọn nhân vật. Khám phá kiến thức.<br>Vượt thử thách để chinh phục từng chặng hành nghề.</p><div class="hero-facts"><span><b>05</b> chặng kiến thức</span><span><b>05</b> huy hiệu hành trình</span></div></div><section class="player-panel">${game.profile?`<div class="welcome-player">${window.playerAvatar(game.profile.avatar)}<span class="level-pill">LEVEL ${completed()+1}</span><p class="eyebrow">CHÀO MỪNG TRỞ LẠI</p><h2>${esc(game.profile.name)}</h2><p>${xp()} XP · ${completed()}/5 huy hiệu</p><a class="primary" href="#${next?nextAction(next):'handbook'}">${next?'Tiếp tục hành trình':'Xem thành tích'} ${icons.arrow}</a><button class="text-button" data-profile>Đổi nhân vật / tên</button></div>`:profileForm()}</section></section><div class="sectionline world-heading"><div><p class="eyebrow">CHỌN BẢN ĐỒ CỦA BẠN</p><h2>Hai bản đồ. Một hành trình nghề nghiệp.</h2></div><span class="tiny-label">01 BẢN ĐỒ ĐANG MỞ</span></div><div class="worlds"><a class="world-card" href="#handbook" data-enter data-tilt><div class="world-top"><span class="eyebrow">BẢN ĐỒ 01</span><span class="availability"><i></i> Sẵn sàng khám phá</span></div><div class="world-illustration handbook-world" aria-hidden="true"><span class="world-building">${icons.briefcase}</span><span class="world-track"></span>${[1,2,3,4,5].map(n=>`<i class="mini-stage s${n}">${n}</i>`).join('')}</div><h2>Cẩm nang hành nghề</h2><p>Đọc hồ sơ, kết nối kiến thức và xử lý tình huống tại bàn tư vấn. Mỗi chặng hoàn thành mở thêm một level.</p><div class="world-foot"><span>${completed()}/5 chặng đã vượt</span><b>Vào bản đồ ${icons.arrow}</b></div></a><a class="world-card forthcoming" href="#journey" data-tilt><div class="world-top"><span class="eyebrow">BẢN ĐỒ 02</span><span class="availability">${icons.lock} Sắp cập nhật</span></div><div class="world-illustration future-world" aria-hidden="true">${icons.compass}<span></span><span></span><span></span></div><h2>CA Journey</h2><p>Nội dung sẽ được cập nhật trong thời gian tới.</p><div class="world-foot"><span>Chưa mở hành trình</span><b>Xem thông tin ${icons.arrow}</b></div></a></div>${footer()}</div>`}
function handbook(){sidebar('handbook');main.innerHTML=crumbs([['Cẩm nang hành nghề']])+pagehead('BẢN ĐỒ 01 / CẨM NANG HÀNH NGHỀ','Từng chặng nhỏ. Nền tảng vững.','Đọc tài liệu, vượt thử thách và thu thập huy hiệu. Hoàn thành một chặng để tăng một level.')+playerHUD()+`<div class="adventure-layout"><section class="career-map" aria-label="Bản đồ năm chặng"><div class="map-grid" aria-hidden="true"></div><div class="map-kicker">HÀNH TRÌNH HÀNH NGHỀ <span>START → LEVEL 6</span></div><ol class="stage-path">${H.chapters.map((c,i)=>{const done=doneChapter(c),current=nextStage()?.id===c.id;return `<li class="stage-node ${done?'cleared':current?'current-stage':'later-stage'}"><a class="stage-link" href="#chapter/${c.id}"><span class="stage-marker">${done?icons.check:String(i+1).padStart(2,'0')}</span><div class="stage-copy"><span class="stage-meta">CHẶNG ${i+1} <b>${done?'ĐÃ VƯỢT':current?'ĐANG CHINH PHỤC':'SẴN SÀNG KHÁM PHÁ'}</b></span><h2>${esc(c.label)}</h2><p>${esc(c.description)}</p><span class="stage-tasks">${objectives(c).map(o=>`<i class="${o.done?'finished':''}" aria-label="${esc(o.label)}: ${o.done?'đã xong':'chưa xong'}">${o.done?'✓':'○'}</i>`).join('')}<small>${done?'Huy hiệu đã mở':objectives(c).filter(o=>o.done).length+'/3 nhiệm vụ'}</small></span></div><span class="stage-arrow">${icons.arrow}</span></a></li>`}).join('')}</ol><div class="finish-marker">${icons.flag}<span>Vững nền tảng. Sẵn sàng vận dụng.</span></div></section><aside class="achievement-panel"><p class="eyebrow">BỘ SƯU TẬP CỦA BẠN</p><h2>Dấu ấn hành trình</h2><div class="badge-shelf">${H.chapters.map((c,i)=>`<div class="badge-card ${doneChapter(c)?'earned':''}"><span>${doneChapter(c)?icons.star:icons.lock}</span><div><b>${esc(G.badges[i])}</b><small>${doneChapter(c)?'Đã nhận · +100 XP':'Hoàn thành chặng '+(i+1)}</small></div></div>`).join('')}</div><details class="xp-guide"><summary>Cách nhận XP & lên level</summary><p>+20 XP cho một nội dung đã đọc; +5 XP cho một quy tắc đã mở; +25 XP cho một câu ôn tập; +80 XP cho một thử thách tương tác; +40 XP cho một hồ sơ tình huống; +100 XP khi hoàn thành chặng.</p><p>Mỗi phần chỉ nhận XP một lần. Hoàn thành 3 nhiệm vụ của một chặng để tăng 1 level. Làm lại không trừ điểm.</p><p>Level và huy hiệu thể hiện tiến độ học trong hành trình.</p></details></aside></div>${footer()}`}
function chapter(id){const c=getChapter(id);if(!c)return notfound();sidebar('handbook',id);const rule=id==='c4';main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label]])+pagehead(`CHẶNG ${H.chapters.indexOf(c)+1} / 5`,c.title)+`<section class="chapter-brief"><div class="chapter-brief-icon">${rule?icons.shield:icons.briefcase}</div><div><p class="eyebrow">NHIỆM VỤ CỦA BẠN</p><h2>${doneChapter(c)?'Chặng đã chinh phục!':'Ba bước để nhận huy hiệu.'}</h2><p>Hoàn thành các mục dưới đây để nhận huy hiệu <b>${esc(G.badges[H.chapters.indexOf(c)])}</b> và tăng 1 level.</p></div><span class="reward-chip">+100 XP</span></section><nav class="objective-list" aria-label="Nhiệm vụ của chặng">${objectives(c).map((o,i)=>`<a href="#${o.href}" class="${o.done?'objective-done':''}"><span>${o.done?'✓':'0'+(i+1)}</span><div><b>${esc(o.label)}</b><small>${o.detail}</small></div>${icons.arrow}</a>`).join('')}</nav><div class="intro">${blocksHTML(c.intro)}</div>`+(rule?`<section class="rule-intro"><div class="rule-intro-icon">${icons.shield}</div><div><p class="eyebrow">HIỂU QUY TẮC TRƯỚC · XỬ LÝ TÌNH HUỐNG SAU</p><h2>Giữ chuẩn trong từng lựa chọn.</h2><p>Khám phá DO & DON'T, xem toàn cảnh, phân loại hành vi rồi bước vào 7 hồ sơ tình huống.</p><a class="primary" href="#rules-guide/do/0">Khám phá 14 quy tắc ${icons.arrow}</a></div></section><nav class="learning-flow"><a href="#rules-guide/do/0">01 · DO & DON'T ${icons.arrow}</a><a href="#summary">02 · Tóm tắt quy tắc ${icons.arrow}</a><a href="#mission/c4">03 · Phân loại & xử lý tình huống ${icons.arrow}</a></nav>`:`${discoveryMap(id)}<div class="sectionline"><h2>Hồ sơ kiến thức của chặng</h2><span class="badge">${c.lessons.filter(l=>state.done[l.id]).length}/${c.lessons.length} đã học</span></div><div class="lesson-grid">${c.lessons.map((l,i)=>`<a class="lesson-tile" href="#lesson/${l.id}/0"><span class="tag">${state.done[l.id]?'✓':String(i+1).padStart(2,'0')}</span><span class="lesson-xp">${state.done[l.id]?'Đã nhận XP':'+20 XP'}</span><strong>${esc(l.title)}</strong><small>Mở hồ sơ ${icons.arrow}</small></a>`).join('')}</div><section class="checkpoint-link"><div><p class="eyebrow">ĐƯA KIẾN THỨC VÀO THỬ THÁCH</p><h2>${esc(G.missions[id].title)}</h2><p>${esc(G.missions[id].brief)}</p></div><a class="primary" href="#mission/${id}">Vào thử thách ${icons.arrow}</a></section>`)+footer()}
function blockHTML(b,interactive=false){if(b.type==='table'){const headers=b.rows[0];if(interactive)return `<p class="hint">Mở từng thẻ để khám phá nội dung.</p><div class="reveal-grid">${b.rows.slice(1).map(row=>`<details><summary>${esc(row[0])}</summary><dl>${row.slice(1).map((v,i)=>`<dt>${esc(headers[i+1]||'')}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`).join('')}</div><details class="source-panel" style="margin-top:18px"><summary>Xem bảng đầy đủ</summary>${blockHTML(b)}</details>`;return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${b.rows.slice(1).map(r=>`<tr>${r.map((t,i)=>i===0?`<th scope="row">${esc(t).replace(/\n/g,'<br>')}</th>`:`<td>${esc(t).replace(/\n/g,'<br>')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const cls=b.style==='List Paragraph'?'bullet':b.style?.startsWith('Heading')?'source-title':b.text.startsWith('Tự hỏi:')?'quote':'';return `<p class="${cls}">${esc(b.text)}</p>`}
function blocksHTML(bs,interactive=false){return `<div class="content-block">${bs.map(b=>blockHTML(b,interactive)).join('')}</div>`}
function discoveryMap(id){
 const maps={
  c1:{title:'Ba trụ neo · chọn để khám phá',items:[['col','COL','Giữ HƯỚNG'],['cop','COP','Giữ CHUẨN'],['coe','COE','Giữ NHỊP']]},
  c2:{title:'Khung 5P · chọn từng trụ cột',items:[['position','Position','Thấu hiểu · Đồng hành · Kết nối'],['perspective','Perspective','Tin cậy · Chuẩn mực · Nhà nghề'],['poa','Pattern of Action','iLead & HWG'],['plan','Plan','FC · OC · SBI'],['principle','Principle','5A']]},
  c3:{title:'VNDGO · chọn từng nhịp',items:[['v','V','Nếp Trà Việt'],['n','N','Nếp La Bàn'],['d','D','Nếp Soi Sáng'],['g','G','Nếp Tích Năng Lực'],['o','O','Nếp Sống Đầu Tư']]}
 };const m=maps[id];if(!m)return '';return `<p class="discovery-label">${m.title}</p><nav class="discovery-map" aria-label="${m.title}">${m.items.map(x=>`<a href="#lesson/${x[0]}/0"><strong>${x[1]}</strong><span>${x[2]}</span><small>${state.done[x[0]]?'✓ Đã học':'Khám phá ↗'}</small></a>`).join('')}</nav>`
}
function chunks(l){const out=[];let group=[],count=0;const flush=()=>{if(group.length)out.push(group);group=[];count=0};for(const b of l.blocks){const n=b.text?.length||500;if(b.type==='table'){flush();out.push([b]);continue}if(count+n>950&&group.length)flush();group.push(b);count+=n}flush();return out}
function lesson(id,n=0){const l=getLesson(id);if(!l)return notfound();if(id==='rules'){to('rules-guide/do/0');return}const c=getChapter(l.chapter),pages=chunks(l);n=Math.max(0,Math.min(Number(n)||0,pages.length-1));sidebar('handbook',c.id);if(!Array.isArray(state.seen[id]))state.seen[id]=[];if(!state.seen[id].includes(n))state.seen[id].push(n);persist();const all=pages.every((_,i)=>state.seen[id].includes(i));main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/'+c.id],['Khám phá']])+pagehead(c.label,l.title)+`<div class="reader"><div class="stepbar" aria-label="Các bước đọc">${pages.map((_,i)=>`<button data-step="${id}/${i}" aria-label="Đọc phần ${i+1} trên ${pages.length}" ${i===n?'aria-current="step"':''} class="${i===n?'active':state.seen[id].includes(i)?'visited':''}"></button>`).join('')}</div><section class="card"><div class="stepmeta"><span>KHÁM PHÁ ${n+1} / ${pages.length}</span><span>Nội dung cẩm nang</span></div>${blocksHTML(pages[n],true)}<div class="actions" style="margin-top:25px">${n>0?`<a class="btn" href="#lesson/${id}/${n-1}">← Phần trước</a>`:''}${n<pages.length-1?`<a class="primary" href="#lesson/${id}/${n+1}">Phần tiếp theo →</a>`:`<span class="badge">Đã đến cuối nội dung</span>`}</div></section>${n===pages.length-1?`<section class="card reflection"><p class="eyebrow">DỪNG LẠI VÀ LIÊN HỆ</p><h2>Bạn sẽ dùng điều này khi nào?</h2><p>Thử nhắc lại một ý quan trọng bằng lời của mình. Sau đó liên hệ với một việc bạn đang hoặc sắp làm.</p><label for="reflect">Ghi chú của bạn (không bắt buộc)</label><textarea id="reflect" data-note="reflect-${id}" placeholder="Một điều tôi sẽ áp dụng…">${esc(state.notes['reflect-'+id]||'')}</textarea><div class="note-tools"><p class="hint">Không nhập dữ liệu nhận diện khách hàng.</p><button data-export>Xuất ghi chú</button></div><div class="actions"><button class="primary" data-complete="${id}" ${all?'':'disabled'}>${state.done[id]?'✓ Đã nhận 20 XP':'Hoàn thành hồ sơ · +20 XP'}</button><a class="btn" href="#${nextLesson(l)}">Nội dung tiếp theo →</a></div>${all?'':'<p class="hint">Mở đủ các phần đọc trước khi ghi nhận hoàn thành.</p>'}</section>`:''}<details class="card source-panel"><summary>Tra toàn bộ nội dung mục này</summary>${blocksHTML(l.blocks)}</details></div>${footer()}`}
function nextLesson(l){const c=getChapter(l.chapter),i=c.lessons.findIndex(x=>x.id===l.id);return i<c.lessons.length-1?'lesson/'+c.lessons[i+1].id+'/0':'mission/'+c.id}
function quoteSources(ids){return [].concat(ids).map(i=>{const b=H.sources[i];return b?`<blockquote>${b.type==='text'?esc(b.text):blockHTML(b)}</blockquote>`:''}).join('')}
function missionDraft(id){const m=G.missions[id];if(!object(game.drafts[id]))game.drafts[id]={};const d=game.drafts[id];if(!object(d.pairs))d.pairs={};if(!object(d.sorted))d.sorted={};if(!Array.isArray(d.order)||d.order.length!==5||new Set(d.order).size!==5||d.order.some(x=>!Number.isInteger(x)||x<0||x>4))d.order=[...(m.order||[0,1,2,3,4])];if(!Array.isArray(d.history))d.history=[];if(!Number.isInteger(d.cursor)||d.cursor<0||d.cursor>14)d.cursor=0;return d}
function missionText(m,i){let t=H.sources[m.sources[i]].text;if(m.stripPrefix)t=t.slice(t.indexOf(':')+1).trim();if(m.removeLabels)t=t.replace(/^(COL|COP|COE)/,'Điểm tựa này');return t}
function mission(id){const c=getChapter(id),m=G.missions[id];if(!c||!m)return notfound();sidebar('handbook',id);const d=missionDraft(id),passed=d.result===true;
 let body='';
 if(m.type==='match'){body=`<div class="match-workspace"><div class="token-bank"><p class="eyebrow">1 · CHỌN MỘT THẺ</p>${m.labels.map((label,i)=>`<button class="match-token ${d.picked===i?'selected':''} ${Object.values(d.pairs).includes(i)?'placed':''}" data-pick="${i}" data-match-drag="${i}" draggable="true" aria-pressed="${d.picked===i}" ${passed?'disabled':''}><span>${esc(label)}</span><small>${Object.values(d.pairs).includes(i)?'Đã ghép':'Chọn thẻ'}</small></button>`).join('')}</div><div class="pair-targets"><p class="eyebrow">2 · CHỌN Ô PHÙ HỢP</p>${m.order.map(i=>`<button class="pair-target ${d.checked?(d.pairs[i]===i?'pair-right':'pair-wrong'):''}" data-place="${i}" data-drop-pair="${i}" ${passed?'disabled':''}><span class="pair-slot">${d.pairs[i]===undefined?'Đặt thẻ vào đây':esc(m.labels[d.pairs[i]])}</span><span>${esc(missionText(m,i))}</span>${d.checked?`<b class="pair-mark">${d.pairs[i]===i?'✓ Khớp':'↻ Cần ghép lại'}</b>`:''}</button>`).join('')}</div></div><p class="hint" role="status">${d.picked!==undefined&&d.picked!==null?'Đã chọn '+esc(m.labels[d.picked])+'. Chọn một ô nội dung để ghép.':'Bấm thẻ rồi bấm ô nội dung, hoặc kéo thẻ vào ô. Có thể thay đổi trước khi kiểm tra.'}</p><button class="primary" data-submit-mission="${id}" ${Object.keys(d.pairs).length===m.labels.length&&!passed?'':'disabled'}>Kiểm tra kết nối ${icons.check}</button>`}
 if(m.type==='order'){const rows=H.sources[m.source].rows.slice(1);body=`<p class="mission-tip">Dựng thứ tự theo hành trình đã học, từ bước đầu tiên đến bước cuối cùng.</p><ol class="order-list">${d.order.map((x,i)=>`<li class="order-card ${d.checked?(x===i?'pair-right':'pair-wrong'):''}" draggable="${!passed}" data-order-id="${x}"><span class="order-number">${i+1}</span><div><h3>${esc(rows[x][1])}</h3><p>${esc(rows[x][2])}</p>${d.checked?`<small>${x===i?'✓ Đúng vị trí':'↻ Xem lại vị trí'}</small>`:''}</div><div class="order-controls"><button data-move="${i}|-1" aria-label="Đưa ${esc(rows[x][1])} lên" ${i===0||passed?'disabled':''}>↑</button><button data-move="${i}|1" aria-label="Đưa ${esc(rows[x][1])} xuống" ${i===4||passed?'disabled':''}>↓</button></div></li>`).join('')}</ol><p class="hint">Có thể dùng nút ↑ ↓ bằng bàn phím hoặc kéo thẻ để đổi vị trí.</p><button class="primary" data-submit-mission="${id}" ${passed?'disabled':''}>Xác nhận hành trình ${icons.check}</button>`}
 if(m.type==='sort'){const count=Object.keys(d.sorted).length,idx=d.cursor<14?d.cursor:-1;body=`<div class="sorting-progress"><progress max="14" value="${count}" aria-label="Thẻ đã phân loại"></progress><span>${count}/14 thẻ đã đặt</span></div>${idx>=0?`<article class="sort-card"><span class="eyebrow">HÀNH VI ${String(idx+1).padStart(2,'0')} / 14</span><p>${esc(m.items[idx].text)}</p><small>Hành vi này thuộc nhóm nào?</small></article><div class="sort-bins"><button class="sort-bin" data-sort="do">${icons.check}<b>DO</b><span>Nên thực hiện</span></button><button class="sort-bin" data-sort="dont">${icons.shield}<b>DON'T</b><span>Không được làm</span></button></div>`:`<div class="sorting-ready">${icons.check}<h2>Đã đặt đủ 14 thẻ.</h2><p>Xem lại cách phân loại rồi kiểm tra kết quả.</p><button class="primary" data-submit-mission="${id}" ${passed?'disabled':''}>Kiểm tra bàn phân loại ${icons.arrow}</button></div>`}<div class="sort-actions"><button data-sort-undo ${!d.history.length||passed?'disabled':''}>↶ Hoàn tác thẻ vừa đặt</button><span class="hint">${count?'Bấm một thẻ bên dưới để đổi nhóm.':'Không tính giờ. Đọc kỹ rồi quyết định.'}</span></div><div class="sort-review">${m.items.map((item,i)=>d.sorted[i]===undefined?'':`<button data-sort-edit="${i}" class="sort-review-card ${d.checked?(d.sorted[i]===item.group?'pair-right':'pair-wrong'):''}" ${passed?'disabled':''}><span>${i+1}</span><p>${esc(item.text)}</p><b>${d.sorted[i]==='do'?'DO':"DON'T"}</b>${d.checked?`<small>${d.sorted[i]===item.group?'✓ Khớp':'↻ Cần đổi nhóm'}</small>`:''}</button>`).join('')}</div>`}
 const refs=m.type==='match'?m.sources:m.type==='order'?[m.source]:m.items.filter((x,i)=>d.sorted[i]!==x.group).map(x=>x.source);
 const result=d.checked?`<section class="mission-feedback feedback ${passed?'positive':'review'}" role="status" tabindex="-1"><h2>${passed?'Nhiệm vụ hoàn tất!':'Chưa khớp hết. Bạn có thể thử lại.'}</h2><p>${passed?'Bạn đã kết nối được kiến thức. +80 XP được ghi nhận một lần cho thử thách này.':'Các thẻ cần xem lại đã được đánh dấu. Đối chiếu căn cứ, chỉnh thẻ rồi kiểm tra lại; không bị trừ XP.'}</p>${!passed?`<details class="source-panel"><summary>Mở căn cứ từ cẩm nang</summary>${quoteSources(refs)}</details>`:''}<div class="actions">${passed?`<a class="primary" href="#${id==='c4'?'rules/0':'check/'+id+'/0'}">${id==='c4'?'Mở 7 hồ sơ tình huống':'Đến trạm kiểm tra'} ${icons.arrow}</a><button data-reset-mission="${id}">Chơi lại thử thách</button>`:''}</div></section>`:'';
 main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/'+id],['Thử thách tương tác']])+pagehead('NHIỆM VỤ / '+({match:'GHÉP THẺ',order:'SẮP XẾP HÀNH TRÌNH',sort:'PHÂN LOẠI HÀNH VI'}[m.type]),m.title,m.brief)+`<section class="mission"><div class="stepmeta"><span>THỰC HÀNH TỪ NỘI DUNG CẨM NANG</span><span class="reward-chip">${game.mastered['mission-'+id]?'✓ Đã nhận 80 XP':'+80 XP'}</span></div>${body}${result}</section>${footer()}`;
}
function submitMission(id){const m=G.missions[id],d=missionDraft(id);let correct=false;if(m.type==='match'){if(m.labels.some((_,i)=>d.pairs[i]===undefined))return;correct=m.labels.every((_,i)=>d.pairs[i]===i)}else if(m.type==='order'){correct=d.order.every((x,i)=>x===i)}else{if(m.items.some((_,i)=>d.sorted[i]===undefined))return;correct=m.items.every((x,i)=>d.sorted[i]===x.group)}d.checked=true;d.result=correct;persist();if(correct)master('mission-'+id,80);render();$('.mission-feedback')?.focus({preventScroll:true})}
function editMission(d){d.checked=false;d.result=false}
function placePair(id,target){const d=missionDraft(id),m=G.missions[id];if(d.result||!Number.isInteger(d.picked)||d.picked<0||d.picked>=m.labels.length||target<0||target>=m.labels.length){toast('Chọn một thẻ trước, rồi chọn ô nội dung.');return}for(const k of Object.keys(d.pairs))if(d.pairs[k]===d.picked)delete d.pairs[k];d.pairs[target]=d.picked;d.picked=null;editMission(d);persist();render();$(`[data-place="${target}"]`)?.focus({preventScroll:true})}
function moveOrder(id,from,toIndex){const d=missionDraft(id);if(d.result||from<0||toIndex<0||from>4||toIndex>4)return;const item=d.order.splice(from,1)[0];d.order.splice(toIndex,0,item);editMission(d);persist();render();$(`[data-order-id="${item}"] button:not(:disabled)`)?.focus({preventScroll:true})}
function practice(type,id,n=0){const rules=type==='rules',c=getChapter(rules?'c4':id),qs=rules?L.scenarios:L.checkpoints[id];if(!c||!qs)return notfound();n=Math.max(0,Math.min(Number(n)||0,qs.length-1));const q=qs[n],aid=rules?q.id:id+'-'+n,a=state.answers[aid];sidebar('handbook',c.id);
 const dest=i=>rules?'rules/'+i:'check/'+id+'/'+i;
 const answered=qs.filter((x,i)=>rules?game.mastered[x.id]:state.answers[id+'-'+i]).length;
 const correct=qs.filter((x,i)=>game.mastered[rules?x.id:id+'-'+i]).length,next=H.chapters[H.chapters.indexOf(c)+1];
 const evidence=rules?G.evidence[n]:null,ev=rules?game.evidence[aid]:null;
 const sourceLabel=s=>H.sources[s].text.split(':')[0];
 const decisionFeedback=a?`<div class="feedback ${a.correct?'positive':'review'}" role="status"><h3>${a.correct?rules?'✓ Cách xử lý phù hợp.':'✓ Lựa chọn phù hợp.':rules?'Chưa phù hợp. Cùng nhìn lại quyết định.':'Hãy đối chiếu rồi thử lại.'}</h3><p>${a.correct?rules?'Bước tiếp theo: xác định quy tắc làm căn cứ cho lựa chọn này.':'+25 XP cho lần chinh phục đầu tiên.':'Đọc lại căn cứ bên dưới. Bạn được thử lại và không mất XP.'}</p>${!rules||!a.correct?`<p class="source-label">Căn cứ từ cẩm nang</p>${quoteSources(rules?q.sources:q.source)}`:''}<button data-retry="${aid}">${a.correct?'Thử một lựa chọn khác':'Thử lại quyết định'}</button></div>`:'';
 const evidenceUI=rules&&a?.correct?`<section class="evidence-step"><p class="eyebrow">BƯỚC 02 / GHÉP QUY TẮC BẢO VỆ QUYẾT ĐỊNH</p><h2>Quy tắc nào khớp nhất với tình huống này?</h2><div class="evidence-options">${evidence.choices.map(s=>`<button data-evidence="${n}|${s}" class="evidence-card ${ev?.selected===s?(ev.correct?'pair-right':'pair-wrong'):''}" ${ev?.correct?'disabled':''}>${icons.shield}<span>${esc(sourceLabel(s))}</span></button>`).join('')}</div>${ev?`<div class="feedback evidence-feedback ${ev.correct?'positive':'review'}" role="status"><h3>${ev.correct?'Hồ sơ đã xử lý trọn vẹn!':'Quy tắc này chưa khớp nhất. Hãy chọn lại.'}</h3><p>${ev.correct?'Bạn đã chọn được cách xử lý và căn cứ phù hợp. +40 XP cho lần hoàn thành đầu tiên.':'Đối chiếu các quy tắc của hồ sơ bên dưới rồi ghép lại.'}</p>${quoteSources(q.sources)}</div>`:''}</section>`:'';
 const firstPending=qs.findIndex((x,i)=>rules?!game.mastered[x.id]:!state.answers[id+'-'+i]);
 const completion=answered===qs.length?`<section class="quiz-completion"><span class="completion-symbol">${icons.flag}</span><div><p class="eyebrow">ĐÃ HOÀN TẤT LƯỢT ${rules?'XỬ LÝ HỒ SƠ':'ÔN TẬP'}</p><h2>${correct}/${qs.length} ${rules?'hồ sơ đã vượt':'câu hỏi đã chinh phục'}</h2><p>${doneChapter(c)?'Đã hoàn thành đủ nhiệm vụ của chặng và nhận huy hiệu.':'Đối chiếu các nhiệm vụ còn lại để hoàn thành chặng và lên level.'}</p><div class="actions">${next?`<a class="primary next-chapter" href="#chapter/${next.id}">Học chương tiếp theo ${icons.arrow}</a>`:`<a class="primary" href="#handbook">Xem bản đồ & huy hiệu ${icons.arrow}</a>`}${!doneChapter(c)?`<a class="btn" href="#${nextAction(c)}">${esc(objectives(c).find(o=>!o.done).label)} ${icons.arrow}</a>`:''}</div></div></section>`:`<div class="quiz-incomplete"><p>Còn ${qs.length-answered} ${rules?'hồ sơ cần xử lý đủ hai bước':'câu chưa trả lời'}.</p><a class="btn" href="#${dest(Math.max(0,firstPending))}">Tiếp tục nhiệm vụ ${icons.arrow}</a></div>`;
 main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/'+c.id],[rules?'Hồ sơ tình huống':'Trạm kiểm tra']])+pagehead(rules?'BÀN TƯ VẤN / TÌNH HUỐNG MÔ PHỎNG':'TRẠM KIỂM TRA / CỦNG CỐ KIẾN THỨC',rules?q.title:'Mở khóa điều bạn đã hiểu.',rules?'Mỗi hồ sơ có hai bước: quyết định cách xử lý và ghép quy tắc làm căn cứ.':'Mỗi câu trả lời phù hợp nhận 25 XP một lần. Có thể thử lại để hiểu chắc hơn.')+`<nav class="question-track" aria-label="Các ${rules?'hồ sơ':'câu hỏi'}">${qs.map((x,i)=>`<a href="#${dest(i)}" ${i===n?'aria-current="step"':''} class="${i===n?'is-current ':''}${game.mastered[rules?x.id:id+'-'+i]?'is-correct':''}" aria-label="${rules?'Hồ sơ':'Câu'} ${i+1}">${game.mastered[rules?x.id:id+'-'+i]?'✓':i+1}</a>`).join('')}</nav><section class="practice ${rules?'case-desk':''}"><div class="stepmeta"><span>${rules?'HỒ SƠ':'CÂU HỎI'} ${n+1} / ${qs.length}</span><span class="reward-chip">${game.mastered[aid]?'✓ Đã nhận XP':rules?'+40 XP':'+25 XP'}</span></div>${rules?`<div class="case-message"><span class="case-person">${icons.user}</span><div><span class="eyebrow">TÌNH HUỐNG TẠI BÀN TƯ VẤN</span><p class="scene">${esc(q.scene)}</p></div></div><p class="eyebrow">BƯỚC 01 / BẠN SẼ XỬ LÝ THẾ NÀO?</p>`:`<p class="scene">${esc(q.q)}</p>`}${q.options.map((o,i)=>`<button class="choice ${a&&i===a.selected?(a.correct?'correct':'wrong'):''}" data-answer="${type}|${id}|${n}|${i}" ${a?'disabled':''}><span class="letter">${rules?icons.arrow:String.fromCharCode(65+i)}</span><span>${esc(o)}</span>${a&&i===a.selected?`<span class="answer-mark">${a.correct?'✓':'↻'}</span>`:''}</button>`).join('')}${decisionFeedback}${evidenceUI}<div class="actions practice-actions">${n>0?`<a class="btn" href="#${dest(n-1)}">← ${rules?'Hồ sơ':'Câu'} trước</a>`:''}${n<qs.length-1?`<a class="${game.mastered[aid]?'primary':'btn'}" href="#${dest(n+1)}">${rules?'Hồ sơ tiếp theo':'Câu tiếp theo'} ${icons.arrow}</a>`:''}</div></section>${n===qs.length-1?completion:''}${footer()}`
}
function answer(type,id,n,i){const q=type==='rules'?L.scenarios[n]:L.checkpoints[id]?.[n];if(!q||!Number.isInteger(i)||i<0||i>=q.options.length)return;const aid=type==='rules'?q.id:id+'-'+n;if(state.answers[aid])return;state.answers[aid]={selected:i,correct:i===q.correct};persist();if(type!=='rules'&&i===q.correct)master(aid,25);render();const feedback=$('.feedback');if(feedback){feedback.tabIndex=-1;feedback.focus({preventScroll:true})}}
function journey(){sidebar(null);main.innerHTML=crumbs([['CA Journey']])+`<section class="journey-coming"><div class="coming-emblem">${icons.compass}<span>${icons.lock}</span></div><p class="eyebrow">BẢN ĐỒ 02</p><h1>CA Journey</h1><p>Nội dung sẽ được cập nhật trong thời gian tới.</p><a class="btn" href="#home">Về trang chủ ${icons.arrow}</a></section>${footer()}`}
function notfound(){sidebar(null);main.innerHTML=crumbs()+pagehead('ĐƯỜNG DẪN','Không tìm thấy nội dung này.')+'<a class="primary" href="#home">Về trang chủ</a>'}
const allRules=()=>[...Array.from({length:7},(_,i)=>({source:227+i,type:'do',index:i})),...Array.from({length:7},(_,i)=>({source:235+i,type:'dont',index:i}))];
function ruleParts(rule){const text=H.sources[rule.source].text,split=text.indexOf(':');return {title:text.slice(0,split),body:text.slice(split+1).trim(),text}}
function ruleSource(rule){const {title,body}=ruleParts(rule);return `<h3>${esc(title)}:</h3> <p>${esc(body)}</p>`}
function ruleGuide(type='do',index=0){
 type=type==='dont'?'dont':'do';index=Math.max(0,Math.min(Number(index)||0,6));const rules=allRules(),rule=rules.find(r=>r.type===type&&r.index===index),abs=rules.indexOf(rule);
 if(!Array.isArray(state.seen.ruleGuide))state.seen.ruleGuide=[];if(!state.seen.ruleGuide.includes(rule.source))state.seen.ruleGuide.push(rule.source);persist();settle();
 sidebar('handbook','c4');const group=rules.filter(r=>r.type===type);const next=rules[abs+1],previous=rules[abs-1];
 main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],['Quy tắc hành vi','chapter/c4'],["Khám phá DO & DON'T"]])+pagehead('01 / HIỂU QUY TẮC TRƯỚC KHI THỰC HÀNH','Mỗi quy tắc, một điều cần giữ.','Chọn từng thẻ để đọc. Sau đó nhìn lại toàn bộ quy tắc và luyện cách xử lý tình huống.')+
 `<div class="rule-toolbar"><nav class="segmented" aria-label="Nhóm quy tắc"><a href="#rules-guide/do/0" ${type==='do'?'aria-current="true"':''}>${icons.check} DO <span>07</span></a><a href="#rules-guide/dont/0" ${type==='dont'?'aria-current="true"':''}>${icons.shield} DON'T <span>07</span></a></nav><span class="badge">Đã mở ${state.seen.ruleGuide.length}/14 quy tắc</span></div>`+
 `<div class="rule-workspace"><nav class="rule-index" aria-label="Chọn quy tắc">${group.map(r=>`<a href="#rules-guide/${r.type}/${r.index}" ${r.index===index?'aria-current="true"':''}><span>${String(r.index+1).padStart(2,'0')}</span><b>${esc(ruleParts(r).title)}</b>${state.seen.ruleGuide.includes(r.source)?'<i aria-label="Đã mở">✓</i>':''}</a>`).join('')}</nav><article class="rule-stage ${type}"><div class="rule-stage-top"><span class="rule-type">${type==='do'?'DO · ĐIỀU DC PHẢI LÀM':"DON'T · ĐIỀU DC KHÔNG ĐƯỢC LÀM"}</span><span class="rule-page">${String(index+1).padStart(2,'0')} <small>/ 07</small></span></div><div class="rule-stage-icon" aria-hidden="true">${type==='do'?icons.check:icons.shield}</div><div class="rule-copy">${ruleSource(rule)}</div><div class="rule-stage-bottom"><span>Nội dung nguyên văn từ cẩm nang</span><div class="actions">${previous?`<a class="btn" href="#rules-guide/${previous.type}/${previous.index}" aria-label="Quy tắc trước">←</a>`:''}${next?`<a class="primary" href="#rules-guide/${next.type}/${next.index}">${type==='do'&&index===6?"Đến DON'T":"Quy tắc tiếp"} ${icons.arrow}</a>`:`<a class="primary" href="#summary">Xem toàn cảnh ${icons.arrow}</a>`}</div></div></article></div><div class="rule-bottom-links"><a class="text-link" href="#summary">Tóm tắt 14 quy tắc →</a><a class="text-link" href="#mission/c4">Đã nắm quy tắc? Thử phân loại →</a></div>${footer()}`;
}
function summary(){sidebar('handbook','c4');const rules=allRules(),good=L.scenarios.filter(s=>game.mastered[s.id]).length;
 main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],['Quy tắc hành vi','chapter/c4'],['Tóm tắt quy tắc']])+pagehead('02 / TOÀN CẢNH QUY TẮC','Giữ chuẩn trong từng lựa chọn.','14 quy tắc để tra trước và sau cuộc gặp. Chọn nhóm cần xem hoặc mở từng quy tắc để đọc tập trung.')+
 `<div class="rule-toolbar"><div class="segmented" role="group" aria-label="Lọc quy tắc"><button data-rule-filter="all" aria-pressed="true">Tất cả <span>14</span></button><button data-rule-filter="do" aria-pressed="false">DO <span>07</span></button><button data-rule-filter="dont" aria-pressed="false">DON'T <span>07</span></button></div><span id="ruleFilterStatus" class="muted" role="status">Đang xem 14 quy tắc</span></div><div class="rule-summary-grid">${['do','dont'].map(type=>`<section class="rule-column" data-rule-group="${type}"><header class="rule-column-head"><span class="rule-column-icon" aria-hidden="true">${type==='do'?icons.check:icons.shield}</span><div><p class="eyebrow">${type==='do'?'CHỦ ĐỘNG THỰC HIỆN':'GIỮ ĐÚNG GIỚI HẠN'}</p><h2>${esc(H.sources[type==='do'?226:234].text)}</h2></div></header>${rules.filter(r=>r.type===type).map(r=>`<article class="rule-summary-card ${type}"><span class="rule-number">${String(r.index+1).padStart(2,'0')}</span><div class="rule-summary-copy">${ruleSource(r)}<a href="#rules-guide/${r.type}/${r.index}" class="rule-read" aria-label="Đọc tập trung: ${esc(ruleParts(r).title)}">Đọc tập trung ${icons.arrow}</a></div></article>`).join('')}</section>`).join('')}</div><section class="checkpoint-link rule-to-test"><div><p class="eyebrow">03 / PHÂN LOẠI TRƯỚC KHI XỬ LÝ TÌNH HUỐNG</p><h2>Sẵn sàng đưa quy tắc vào thực hành?</h2><p>Đặt 14 thẻ hành vi vào DO hoặc DON'T, rồi xử lý 7 hồ sơ tình huống tại bàn tư vấn.</p></div><a class="primary" href="#mission/c4">Vào bàn phân loại ${icons.arrow}</a></section>${footer()}`
}
function render(){const old=route;route=location.hash.slice(1)||'home';const aliases={'cam-nang':'handbook','ca-journey':'journey','trang-chu':'home'};if(aliases[route]){location.replace('#'+aliases[route]);return}if(/^c[0-4]$/.test(route)){location.replace('#chapter/'+route);return}if(route!==old&&!backing)trail.push(route);backing=false;const p=route.split('/');document.body.dataset.page=p[0];if(!['home','journey'].includes(p[0])){state.last=route;persist()}
 if(p[0]==='home')home();else if(p[0]==='handbook')handbook();else if(p[0]==='chapter')chapter(p[1]);else if(p[0]==='lesson')lesson(p[1],p[2]);else if(p[0]==='mission')mission(p[1]);else if(p[0]==='check')practice('check',p[1],p[2]);else if(p[0]==='rules')practice('rules','c4',p[1]);else if(p[0]==='summary')summary();else if(p[0]==='rules-guide')ruleGuide(p[1],p[2]);else if(p[0]==='journey')journey();else notfound();
 const profileButton=$('#profileOpen');profileButton.innerHTML=`${icons.user}<span>${game.profile?'Level '+(completed()+1):'Nhân vật'}</span>`;profileButton.setAttribute('aria-label',game.profile?'Sửa hồ sơ của '+game.profile.name:'Tạo nhân vật');
 if(p[0]!=='home')document.title=(main.querySelector('h1')?.textContent||'Cẩm nang')+' · VNDIRECT';if(old!==route){window.scrollTo(0,0);main.focus({preventScroll:true});window.HandbookUI.animate(main)}}
function exportNotes(){const entries=Object.entries(state.notes).filter(([k,v])=>k.startsWith('reflect-')&&typeof v==='string'&&v.trim());if(!entries.length){toast('Bạn chưa có ghi chú để xuất.');return}const lines=['GHI CHÚ HỌC TẬP · VNDIRECT',new Date().toLocaleDateString('vi-VN'),''];for(const [k,v]of entries)lines.push(getLesson(k.slice(8))?.title||k,v,'');const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Ghi-chu-hoc-tap-VNDIRECT.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
const records=lessons.flatMap(l=>l.id==='rules'?[{title:l.title,href:'summary',text:l.blocks.map(b=>b.text||b.rows.flat().join(' ')).join(' ')}]:chunks(l).map((bs,i)=>({title:l.title,href:'lesson/'+l.id+'/'+i,text:bs.map(b=>b.text||b.rows.flat().join(' ')).join(' ')})));
function search(){const q=norm($('#searchInput').value.trim());const results=records.filter(r=>norm(r.title+' '+r.text).includes(q));$('#searchResults').innerHTML=q?results.map(r=>{const hit=norm(r.text).indexOf(q),start=Math.max(0,hit-50);return `<a href="#${r.href}" data-search-result><strong>${esc(r.title)}</strong><p>${start?'…':''}${esc(r.text.slice(start,start+180))}…</p></a>`}).join('')||'<p class="no-results">Chưa tìm thấy. Thử một từ khóa khác hoặc bỏ dấu tiếng Việt.</p>':'<p class="no-results">Tìm nội dung trong Cẩm nang hành nghề.</p>'}
document.addEventListener('submit',e=>{const f=e.target.closest('[data-profile-form]');if(!f)return;e.preventDefault();const name=f.elements.playerName.value.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,32);if(!name){f.elements.playerName.focus();toast('Nhập tên bạn muốn dùng trong hành trình.');return}game.profile={name,avatar:f.elements.avatar.value==='female'?'female':'male'};persist();const inDialog=$('#profileDialog').contains(f);if(inDialog)$('#profileDialog').close();if(!inDialog)to('handbook');else render();toast('Đã sẵn sàng, '+name+'!')});
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
 if(b.classList.contains('skip')){e.preventDefault();main.focus();return}
 if(b.hasAttribute('data-profile'))openProfile();
 if(b.hasAttribute('data-enter')&&!game.profile){e.preventDefault();openProfile()}
 if(b.matches('[data-back]')&&trail.length>1){trail.pop();backing=true;to(trail[trail.length-1])}
 if(b.dataset.step)to('lesson/'+b.dataset.step);
 if(b.dataset.answer){const[t,id,n,i]=b.dataset.answer.split('|');answer(t,id,+n,+i)}
 if(b.dataset.retry){delete state.answers[b.dataset.retry];delete game.evidence[b.dataset.retry];persist();render();$('.choice')?.focus({preventScroll:true})}
 if(b.dataset.evidence){const[n,s]=b.dataset.evidence.split('|').map(Number),q=L.scenarios[n],v=G.evidence[n];if(!q||!state.answers[q.id]?.correct||!v.choices.includes(s))return;game.evidence[q.id]={selected:s,correct:s===v.correct};persist();if(s===v.correct)master(q.id,40);render();const f=$('.evidence-feedback');if(f){f.tabIndex=-1;f.focus({preventScroll:true})}}
 if(b.dataset.complete){const l=getLesson(b.dataset.complete);if(!l||!chunks(l).every((_,i)=>Array.isArray(state.seen[l.id])&&state.seen[l.id].includes(i)))return;const fresh=!state.done[l.id];state.done[l.id]=true;persist();settle(fresh?['+20 XP','Đã hoàn thành hồ sơ kiến thức.']:null);render();toast('Đã ghi nhận hồ sơ kiến thức.')}
 if(b.dataset.ruleFilter){const type=b.dataset.ruleFilter;document.querySelectorAll('[data-rule-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.ruleFilter===type)));document.querySelectorAll('[data-rule-group]').forEach(x=>x.hidden=type!=='all'&&x.dataset.ruleGroup!==type);$('.rule-summary-grid').classList.toggle('filtered',type!=='all');$('#ruleFilterStatus').textContent=type==='all'?'Đang xem 14 quy tắc':'Đang xem 7 quy tắc '+(type==='do'?'DO':"DON'T");}
 const id=route.split('/')[0]==='mission'?route.split('/')[1]:null;
 if(id&&G.missions[id]){const d=missionDraft(id),m=G.missions[id];
  if(b.hasAttribute('data-pick')&&!d.result){d.picked=+b.dataset.pick;persist();render();$(`[data-pick="${d.picked}"]`)?.focus({preventScroll:true})}
  if(b.hasAttribute('data-place'))placePair(id,+b.dataset.place);
  if(b.dataset.move){const[from,delta]=b.dataset.move.split('|').map(Number);moveOrder(id,from,from+delta)}
  if(b.dataset.sort&&!d.result&&d.cursor<14){const idx=d.cursor;d.history.push({index:idx,previous:d.sorted[idx]});d.sorted[idx]=b.dataset.sort;d.cursor=m.items.findIndex((_,i)=>d.sorted[i]===undefined);if(d.cursor<0)d.cursor=14;editMission(d);persist();render();$('.sort-card')?.animate?.([{opacity:.4,transform:'translateX(12px)'},{opacity:1,transform:'translateX(0)'}],{duration:document.body.classList.contains('reduce-motion')?0:200});const card=$('.sort-card')||$('.sorting-ready');if(card){card.tabIndex=-1;card.focus({preventScroll:true})}}
  if(b.hasAttribute('data-sort-undo')&&!d.result&&d.history.length){const last=d.history.pop();if(last.previous===undefined)delete d.sorted[last.index];else d.sorted[last.index]=last.previous;d.cursor=last.index;editMission(d);persist();render()}
  if(b.hasAttribute('data-sort-edit')&&!d.result){d.cursor=+b.dataset.sortEdit;editMission(d);persist();render();$('.sort-card')?.scrollIntoView?.({block:'center',behavior:document.body.classList.contains('reduce-motion')?'auto':'smooth'})}
  if(b.dataset.submitMission===id)submitMission(id);
  if(b.dataset.resetMission===id){delete game.drafts[id];persist();render();toast('Thử thách đã làm mới. XP đã nhận được giữ nguyên.')}
 }
 if(b.hasAttribute('data-export'))exportNotes();if(b.hasAttribute('data-search-result'))$('#searchDialog').close();
});
document.addEventListener('dragstart',e=>{const token=e.target.closest('[data-match-drag]'),card=e.target.closest('[data-order-id]');if(token)e.dataTransfer?.setData('text/plain','pair:'+token.dataset.matchDrag);if(card)e.dataTransfer?.setData('text/plain','order:'+card.dataset.orderId)});
document.addEventListener('dragover',e=>{if(e.target.closest('[data-drop-pair],[data-order-id]'))e.preventDefault()});
document.addEventListener('drop',e=>{const id=route.startsWith('mission/')?route.split('/')[1]:null;if(!G.missions[id])return;const value=e.dataTransfer?.getData('text/plain')||'',target=e.target.closest('[data-drop-pair]'),card=e.target.closest('[data-order-id]');if(target&&/^pair:\d+$/.test(value)){e.preventDefault();missionDraft(id).picked=Number(value.split(':')[1]);placePair(id,+target.dataset.dropPair)}if(card&&/^order:[0-4]$/.test(value)){e.preventDefault();const d=missionDraft(id);moveOrder(id,d.order.indexOf(Number(value.split(':')[1])),d.order.indexOf(+card.dataset.orderId))}});
document.addEventListener('input',e=>{if(e.target.dataset.note?.startsWith('reflect-')){state.notes[e.target.dataset.note]=e.target.value;persist()}});
$('#menuToggle').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open))});
main.addEventListener('click',()=>{if($('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false')}});
$('#profileOpen').addEventListener('click',openProfile);
$('#searchOpen').addEventListener('click',()=>{$('#searchDialog').showModal();search();$('#searchInput').focus()});$('#searchInput').addEventListener('input',search);
window.addEventListener('hashchange',render);render();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
