(() => {
'use strict';
const H=window.HANDBOOK,L=window.LEARNING,$=s=>document.querySelector(s), main=$('#main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='vndirect-onboarding-0.5';let canStore=true, saved={};
try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){canStore=false}
if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
const state={done:{},seen:{},answers:{},notes:{},last:'',...saved};
for(const k of ['done','seen','answers','notes'])if(!state[k]||typeof state[k]!=='object')state[k]={};
const lessons=H.chapters.flatMap(c=>c.lessons.map(l=>({...l,chapter:c.id})));
const getLesson=id=>lessons.find(l=>l.id===id),getChapter=id=>H.chapters.find(c=>c.id===id);
let route='', trail=[],backing=false,toastTimer;
const persist=()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch(e){canStore=false}};
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3200)}
function to(path){if(location.hash.slice(1)===path)render();else location.hash=path}
function doneChapter(c){return c.id==='c4'?L.scenarios.every(s=>state.answers[s.id]?.correct):c.lessons.every(l=>state.done[l.id])&&(L.checkpoints[c.id]||[]).every((q,i)=>state.answers[c.id+'-'+i]?.correct)}
const completed=()=>H.chapters.filter(doneChapter).length;
const journeyDone=()=>L.journey.filter(j=>state.done[j.id]).length;
function footer(){return `<footer class="footer"><span>VNDIRECT · Phiên bản ${H.version} · Nội dung ${H.date}</span><span>${canStore?'Tiến độ lưu trên trình duyệt này.':'Trình duyệt không cho lưu tiến độ lâu dài.'} Không đồng bộ điểm LMS.</span></footer>`}
function crumbs(parts=[]){return `<nav class="crumbs" aria-label="Đường dẫn"><a href="#home">Trang chủ</a>${parts.map((p,i)=>`<span aria-hidden="true">/</span>${p[1]?`<a href="#${p[1]}">${esc(p[0])}</a>`:`<span aria-current="page">${esc(p[0])}</span>`}`).join('')}<button data-back ${trail.length<2?'disabled':''}>← Trang vừa xem</button></nav>`}
const pagehead=(eyebrow,title,desc='')=>`<header class="pagehead"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1>${desc?`<p>${esc(desc)}</p>`:''}</header>`;
function sidebar(path,chapter){const side=$('#sidebar');$('#layout').classList.toggle('with-side',!!path);side.hidden=!path;$('#menuToggle').hidden=!path;side.classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false');if(!path){side.innerHTML='';return}
side.innerHTML=`<div class="sidehead">${path==='handbook'?'05 CHƯƠNG HỌC':'06 CHƯƠNG SUY NGẪM'}</div>`+(path==='handbook'?H.chapters.map((c,i)=>`<details ${chapter===c.id?'open':''}><summary class="${chapter===c.id?'current':''}"><span class="navnum">${String(i+1).padStart(2,'0')}</span><span>${esc(c.label)}</span>${doneChapter(c)?'<span aria-label="Đã hoàn thành">✓</span>':''}</summary><div class="subnav"><a href="#chapter/${c.id}" class="${route==='chapter/'+c.id?'active':''}">Tổng quan chương</a>${c.id==='c4'?`<a href="#rules/0">Luyện 7 tình huống</a><a href="#summary">Tóm tắt quy tắc</a>`:c.lessons.map(l=>`<a href="#lesson/${l.id}/0" class="${route.startsWith('lesson/'+l.id+'/')?'active':''}">${state.done[l.id]?'✓ ':''}${esc(l.title)}</a>`).join('')+`<a href="#check/${c.id}/0">Ôn tập chương</a>`}</div></details>`).join(''):L.journey.map((j,i)=>`<a href="#journey/${j.id}" class="${route==='journey/'+j.id?'active':''}"><span class="navnum">${String(i+1).padStart(2,'0')}</span><span>${esc(j.title)} ${state.done[j.id]?'✓':''}</span></a>`).join(''))+`<div class="side-progress"><small>${path==='handbook'?completed()+'/5 chương hoàn thành':journeyDone()+'/6 suy ngẫm đã ghi nhận'}</small><progress max="${path==='handbook'?5:6}" value="${path==='handbook'?completed():journeyDone()}" aria-label="Tiến độ"></progress><p class="hint">Chọn chương theo nhu cầu hoặc học lần lượt.</p></div>`;
}
function home(){sidebar(null);document.title='VNDIRECT · Hành trình hội nhập';main.innerHTML=`<div class="home"><section class="home-hero"><div class="hero-copy"><p class="eyebrow">VNDIRECT / ONBOARDING</p><h1>Hiểu nền tảng.<br>Thực hành mỗi ngày.</h1><p>${esc(H.subtitle)}</p>${state.last?`<a class="btn" href="#${esc(state.last)}">Tiếp tục nơi bạn đã dừng ↗</a>`:''}</div><div class="hero-art" aria-hidden="true"><div class="orb"><span>DC<b>Your Career House</b></span></div><span class="chip one">Khám phá</span><span class="chip two">Thực hành</span><span class="chip three">Vận dụng</span></div></section><div class="portals"><a class="portal" href="#handbook"><div class="number"><span>01 / NỀN TẢNG HÀNH NGHỀ</span><span>↗</span></div><h2>Cẩm nang hành nghề</h2><p>5 chương để hiểu tổ chức, khám phá cách làm việc và luyện lựa chọn trong công việc.</p><div class="foot"><span>${completed()?completed()+'/5 chương hoàn thành':'Bắt đầu khám phá'}</span><span class="arrow">→</span></div></a><a class="portal" href="#journey"><div class="number"><span>02 / NHÌN LẠI HÀNH TRÌNH</span><span>↗</span></div><h2>CA Journey</h2><p>CA 360 – Internal Customer View<br>6 câu hỏi để nhìn lại vai trò, giá trị và nhu cầu phát triển.</p><div class="foot"><span>${journeyDone()?journeyDone()+'/6 suy ngẫm đã ghi nhận':'Khám phá 6 góc nhìn'}</span><span class="arrow">→</span></div></a></div><div class="home-note"><p>Học theo nhịp của bạn. Có thể tra cứu bất cứ lúc nào.</p><p>Không tính giờ · Được thử lại · Có phản hồi</p></div>${footer()}</div>`}
function handbook(){sidebar('handbook');main.innerHTML=crumbs([['Cẩm nang hành nghề']])+pagehead('LỘ TRÌNH 01 · 5 CHƯƠNG','Từ hiểu tổ chức đến thực hành.',H.audience)+`<div class="map" aria-label="Sơ đồ 5 chương">${H.chapters.map((c,i)=>`<a href="#chapter/${c.id}"><span class="num">CHƯƠNG ${String(i+1).padStart(2,'0')}</span><h3>${esc(c.label)}</h3><p>${esc(c.description)}</p><span class="status">${doneChapter(c)?'✓ Đã hoàn thành':'Khám phá chương →'}</span></a>`).join('')}</div><div class="mode-note">Mỗi chương gồm khám phá nội dung và thực hành có phản hồi. Bạn có thể chọn thẳng chủ đề cần dùng, không cần mở khóa tuần tự.</div>${footer()}`}
function blockHTML(b,interactive=false){if(b.type==='table'){const headers=b.rows[0];if(interactive)return `<p class="hint">Mở từng thẻ để khám phá nội dung.</p><div class="reveal-grid">${b.rows.slice(1).map(row=>`<details><summary>${esc(row[0])}</summary><dl>${row.slice(1).map((v,i)=>`<dt>${esc(headers[i+1]||'')}</dt><dd>${esc(v)}</dd>`).join('')}</dl></details>`).join('')}</div><details class="source-panel" style="margin-top:18px"><summary>Xem bảng đầy đủ</summary>${blockHTML(b)}</details>`;return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${b.rows.slice(1).map(r=>`<tr>${r.map((t,i)=>i===0?`<th scope="row">${esc(t).replace(/\n/g,'<br>')}</th>`:`<td>${esc(t).replace(/\n/g,'<br>')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const cls=b.style==='List Paragraph'?'bullet':b.style?.startsWith('Heading')?'source-title':b.text.startsWith('Tự hỏi:')?'quote':'';return `<p class="${cls}">${esc(b.text)}</p>`}
function blocksHTML(bs,interactive=false){return `<div class="content-block">${bs.map(b=>blockHTML(b,interactive)).join('')}</div>`}
function chapter(id){const c=getChapter(id);if(!c)return notfound();sidebar('handbook',id);const rule=id==='c4';main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label]])+pagehead(`CHƯƠNG ${H.chapters.indexOf(c)+1} / 5`,c.title)+`<div class="intro">${blocksHTML(c.intro)}</div>`+(rule?`<section class="card"><p class="eyebrow">THỬ QUYẾT ĐỊNH · NHẬN PHẢN HỒI</p><h2>Bạn sẽ xử lý thế nào?</h2><p>Đi qua 7 tình huống thường gặp trong công việc. Mỗi lựa chọn đều có phản hồi và quy tắc để đối chiếu.</p><p class="hint">Tình huống mô phỏng để luyện tập, được biên soạn từ các quy tắc trong cẩm nang.</p><div class="actions"><a class="primary" href="#rules/0">Bắt đầu luyện tập →</a><a class="btn" href="#summary">Tra bảng tóm tắt</a></div></section><div class="map">${L.scenarios.map((s,i)=>`<a href="#rules/${i}"><span class="num">TÌNH HUỐNG ${i+1}</span><h3>${esc(s.title)}</h3><span class="status">${state.answers[s.id]?.correct?'✓ Đã luyện':'Khám phá →'}</span></a>`).join('')}</div>`:`<div class="sectionline"><h2>Khám phá từng nội dung</h2><span class="badge">${c.lessons.filter(l=>state.done[l.id]).length}/${c.lessons.length} đã học</span></div><div class="lesson-grid ${id==='c1'?'pillars':''}">${c.lessons.map((l,i)=>`<a class="lesson-tile" href="#lesson/${l.id}/0"><span class="tag">${state.done[l.id]?'✓':i+1}</span><strong>${esc(l.title)}</strong><small>Khám phá · Tự liên hệ →</small></a>`).join('')}</div><div class="checkpoint-link"><div><h3 style="margin-bottom:5px">Dừng một nhịp, kiểm tra điều đã hiểu.</h3><small>${L.checkpoints[id].length} câu hỏi · Có thể thử lại</small></div><a class="btn" href="#check/${id}/0">Ôn tập chương →</a></div>`)+`${doneChapter(c)?'<p class="chapter-done">✓ Bạn đã hoàn thành chương này.</p>':''}${footer()}`}
function chunks(l){const out=[];let group=[],count=0;const flush=()=>{if(group.length)out.push(group);group=[];count=0};for(const b of l.blocks){const n=b.text?.length||500;if(b.type==='table'){flush();out.push([b]);continue}if(count+n>950&&group.length)flush();group.push(b);count+=n}flush();return out}
function lesson(id,n=0){const l=getLesson(id);if(!l)return notfound();if(id==='rules'){to('rules/0');return}const c=getChapter(l.chapter),pages=chunks(l);n=Math.max(0,Math.min(Number(n)||0,pages.length-1));sidebar('handbook',c.id);state.seen[id]??=[];if(!state.seen[id].includes(n))state.seen[id].push(n);persist();const all=pages.every((_,i)=>state.seen[id].includes(i));main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/'+c.id],['Khám phá']])+pagehead(c.label,l.title)+`<div class="reader"><div class="stepbar" aria-label="Các bước đọc">${pages.map((_,i)=>`<button data-step="${id}/${i}" aria-label="Đọc phần ${i+1} trên ${pages.length}" ${i===n?'aria-current="step"':''} class="${i===n?'active':state.seen[id].includes(i)?'visited':''}"></button>`).join('')}</div><section class="card"><div class="stepmeta"><span>KHÁM PHÁ ${n+1} / ${pages.length}</span><span>Nội dung cẩm nang</span></div>${blocksHTML(pages[n],true)}<div class="actions" style="margin-top:25px">${n>0?`<a class="btn" href="#lesson/${id}/${n-1}">← Phần trước</a>`:''}${n<pages.length-1?`<a class="primary" href="#lesson/${id}/${n+1}">Phần tiếp theo →</a>`:`<span class="badge">Đã đến cuối nội dung</span>`}</div></section>${n===pages.length-1?`<section class="card reflection"><p class="eyebrow">DỪNG LẠI VÀ LIÊN HỆ</p><h2>Bạn sẽ dùng điều này khi nào?</h2><p>Thử nhắc lại một ý quan trọng bằng lời của mình. Sau đó liên hệ với một việc bạn đang hoặc sắp làm.</p><label for="reflect">Ghi chú của bạn (không bắt buộc)</label><textarea id="reflect" data-note="reflect-${id}" placeholder="Một điều tôi sẽ áp dụng…">${esc(state.notes['reflect-'+id]||'')}</textarea><p class="hint">Ghi chú lưu trên trình duyệt này. Không nhập dữ liệu nhận diện khách hàng.</p><div class="actions"><button class="primary" data-complete="${id}" ${all?'':'disabled'}>${state.done[id]?'✓ Đã ghi nhận hoàn thành':'Đã đọc và tự liên hệ'}</button><a class="btn" href="#${nextLesson(l)}">Nội dung tiếp theo →</a></div>${all?'':'<p class="hint">Mở đủ các phần đọc trước khi ghi nhận hoàn thành.</p>'}</section>`:''}<details class="card source-panel"><summary>Tra toàn bộ nội dung mục này</summary>${blocksHTML(l.blocks)}</details></div>${footer()}`}
function nextLesson(l){const c=getChapter(l.chapter),i=c.lessons.findIndex(x=>x.id===l.id);return i<c.lessons.length-1?'lesson/'+c.lessons[i+1].id+'/0':'check/'+c.id+'/0'}
function quoteSources(ids){return [].concat(ids).map(i=>{const b=H.sources[i];return b?`<blockquote>${b.type==='text'?esc(b.text):blockHTML(b)}</blockquote>`:''}).join('')}
function practice(type,id,n=0){const rules=type==='rules',c=getChapter(rules?'c4':id),qs=rules?L.scenarios:L.checkpoints[id];if(!c||!qs)return notfound();n=Math.max(0,Math.min(Number(n)||0,qs.length-1));const q=qs[n],aid=rules?q.id:id+'-'+n,a=state.answers[aid];sidebar('handbook',c.id);const dest=i=>rules?'rules/'+i:'check/'+id+'/'+i;main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/'+c.id],[rules?'Thực hành':'Ôn tập']])+pagehead(rules?'TÌNH HUỐNG MÔ PHỎNG':'KIỂM TRA ĐIỀU ĐÃ HIỂU',rules?q.title:'Dừng một nhịp, nhớ lại.')+`<section class="practice"><div class="stepmeta"><span>${rules?'TÌNH HUỐNG':'CÂU HỎI'} ${n+1} / ${qs.length}</span><span>Đã luyện đúng ${qs.filter((x,i)=>state.answers[rules?x.id:id+'-'+i]?.correct).length}/${qs.length}</span></div><p class="scene">${esc(rules?q.scene:q.q)}</p>${q.options.map((o,i)=>`<button class="choice ${a&&i===a.selected?(a.correct?'correct':'wrong'):''}" data-answer="${type}|${id}|${n}|${i}" ${a?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}${a?`<div class="feedback" role="status"><h3>${a.correct?'✓ Lựa chọn phù hợp.':'Hãy đối chiếu rồi thử lại.'}</h3><p>${a.correct?'Bạn có thể nối lựa chọn này với quy tắc dưới đây.':'Lựa chọn này chưa phù hợp với nội dung cẩm nang. Đọc căn cứ dưới đây trước khi chọn lại.'}</p><p class="source-label">Căn cứ từ cẩm nang</p>${quoteSources(rules?q.sources:q.source)}<button data-retry="${aid}">${a.correct?'Làm lại câu này':'Thử lại câu này'}</button></div>`:''}<div class="actions" style="margin-top:25px">${n>0?`<a class="btn" href="#${dest(n-1)}">← Câu trước</a>`:''}${n<qs.length-1?`<a class="${a?.correct?'primary':'btn'}" href="#${dest(n+1)}">${a?.correct?'Tiếp theo':'Để sau, xem câu tiếp'} →</a>`:`<a class="primary" href="#${rules?'summary':'chapter/'+id}">${rules?'Xem tóm tắt quy tắc':'Về tổng quan chương'} →</a>`}</div></section>${footer()}`}
function summary(){sidebar('handbook','c4');const c=getChapter('c4'),good=Object.keys(state.answers).filter(k=>/^r[1-7]$/.test(k)&&state.answers[k].correct).length;main.innerHTML=crumbs([['Cẩm nang hành nghề','handbook'],[c.label,'chapter/c4'],['Tóm tắt']])+pagehead('SAU THỰC HÀNH · TRA CỨU','Giữ chuẩn trong từng lựa chọn.',`Bạn đã luyện đúng ${good}/7 tình huống. Có thể quay lại bất kỳ tình huống nào.`)+`<div class="actions"><a class="primary" href="#rules/${Math.max(0,L.scenarios.findIndex(s=>!state.answers[s.id]?.correct))}">${good===7?'Luyện lại tình huống':'Tiếp tục luyện tập'} →</a></div>${good===7?'<div class="finish"><span class="badge">✓ Hoàn thành thực hành</span><h2 style="margin-top:15px">Bạn đã đi qua 7 tình huống.</h2><p>Dùng các quy tắc dưới đây để tra trước và sau cuộc gặp.</p></div>':''}<div class="summary-list" style="margin-top:25px"><section class="card"><h2>${esc(H.sources[226].text)}</h2><ul>${Array.from({length:7},(_,i)=>`<li>${esc(H.sources[227+i].text)}</li>`).join('')}</ul></section><section class="card"><h2>${esc(H.sources[234].text)}</h2><ul>${Array.from({length:7},(_,i)=>`<li>${esc(H.sources[235+i].text)}</li>`).join('')}</ul></section></div>${footer()}`}
function journey(id){sidebar('journey');if(!id){main.innerHTML=crumbs([['CA Journey']])+pagehead('LỘ TRÌNH 02 · 6 CHƯƠNG','CA 360 – Internal Customer View','Sáu góc nhìn để kết nối điều đã học với vai trò và công việc của bạn.')+`<div class="mode-note">Đây là hoạt động suy ngẫm theo 6 câu hỏi CA 360. Không có đáp án chấm điểm; hãy dùng ghi chú để trao đổi với người hướng dẫn.</div><div class="map jmap">${L.journey.map((j,i)=>`<a href="#journey/${j.id}"><span class="num">GÓC NHÌN ${String(i+1).padStart(2,'0')}</span><h3>${esc(j.title)}</h3><p>${esc(j.prompt)}</p><span class="status">${state.done[j.id]?'✓ Đã ghi nhận suy ngẫm':'Viết điều bạn nhận ra →'}</span></a>`).join('')}</div><div class="actions" style="margin-top:25px"><button data-export>Xuất ghi chú của tôi</button></div>${footer()}`;return}
const j=L.journey.find(x=>x.id===id);if(!j)return notfound();const idx=L.journey.indexOf(j);main.innerHTML=crumbs([['CA Journey','journey'],['Góc nhìn '+(idx+1)]])+`<div class="journey-head"><span class="journey-no">0${idx+1}</span>${pagehead('CA 360 · SUY NGẪM',j.title,j.prompt)}</div><section class="card reflection"><p class="eyebrow">LIÊN HỆ VỚI CÔNG VIỆC CỦA BẠN</p>${j.fields.map((f,i)=>`<label for="${id}-${i}">${esc(f)}</label><textarea id="${id}-${i}" data-note="${id}-${i}" placeholder="Viết suy nghĩ của bạn…">${esc(state.notes[id+'-'+i]||'')}</textarea>`).join('')}<p class="hint">Ghi chú tự lưu trên trình duyệt này. Không nhập tên khách hàng, thông tin tài khoản hoặc dữ liệu cá nhân của khách.</p><div class="actions"><button class="primary" data-jcomplete="${id}">${state.done[id]?'✓ Đã ghi nhận suy ngẫm':'Ghi nhận suy ngẫm'}</button>${idx<5?`<a class="btn" href="#journey/${L.journey[idx+1].id}">Góc nhìn tiếp theo →</a>`:`<a class="btn" href="#journey">Về tổng quan</a>`}<button data-export>Xuất ghi chú</button></div></section><section class="card"><h2>Đọc lại để có thêm góc nhìn</h2><p class="muted">Nội dung liên quan trong cẩm nang:</p><div class="actions">${j.links.map(l=>`<a class="btn" href="#lesson/${l}/0">${esc(getLesson(l).title)} ↗</a>`).join('')}</div></section>${footer()}`}
function notfound(){sidebar(null);main.innerHTML=crumbs()+pagehead('ĐƯỜNG DẪN','Không tìm thấy nội dung này.')+'<a class="primary" href="#home">Về trang chủ</a>'}
function render(){const old=route;route=location.hash.slice(1)||'home';const aliases={'cam-nang':'handbook','ca-journey':'journey','trang-chu':'home'};if(aliases[route]){location.replace('#'+aliases[route]);return}if(/^c[0-4]$/.test(route)){location.replace('#chapter/'+route);return}if(route!==old&&!backing)trail.push(route);backing=false;const p=route.split('/');if(p[0]!=='home'){state.last=route;persist()}
if(p[0]==='home')home();else if(p[0]==='handbook')handbook();else if(p[0]==='chapter')chapter(p[1]);else if(p[0]==='lesson')lesson(p[1],p[2]);else if(p[0]==='check')practice('check',p[1],p[2]);else if(p[0]==='rules')practice('rules','c4',p[1]);else if(p[0]==='summary')summary();else if(p[0]==='journey')journey(p[1]);else notfound();if(p[0]!=='home')document.title=(main.querySelector('h1')?.textContent||'Cẩm nang')+' · VNDIRECT';if(old!==route){window.scrollTo(0,0);main.focus({preventScroll:true})}}
function answer(type,id,n,i){const q=type==='rules'?L.scenarios[n]:L.checkpoints[id]?.[n];if(!q)return;const aid=type==='rules'?q.id:id+'-'+n;state.answers[aid]={selected:i,correct:i===q.correct};persist();render();const feedback=$('.feedback');if(feedback){feedback.tabIndex=-1;feedback.focus({preventScroll:true})}}
function exportNotes(){const entries=Object.entries(state.notes).filter(([,v])=>v.trim());if(!entries.length){toast('Bạn chưa có ghi chú để xuất.');return}const lines=['GHI CHÚ HỌC TẬP · VNDIRECT',new Date().toLocaleDateString('vi-VN'),''];for(const [k,v]of entries){let label=k;if(k.startsWith('reflect-'))label=getLesson(k.slice(8))?.title||k;else{const [j,i]=k.split('-'),x=L.journey.find(x=>x.id===j);if(x)label=x.title+' — '+x.fields[+i]}lines.push(label,v,'')}const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Ghi-chu-hoc-tap-VNDIRECT.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
const records=[...lessons.flatMap(l=>(l.id==='rules'?[{title:l.title,href:'summary',text:l.blocks.map(b=>b.text||b.rows.flat().join(' ')).join(' ')}]:chunks(l).map((bs,i)=>({title:l.title,href:'lesson/'+l.id+'/'+i,text:bs.map(b=>b.text||b.rows.flat().join(' ')).join(' ')})))),...L.journey.map(j=>({title:j.title,href:'journey/'+j.id,text:j.prompt}))];
function search(){const q=norm($('#searchInput').value.trim());const results=records.filter(r=>norm(r.title+' '+r.text).includes(q));$('#searchResults').innerHTML=q?results.map(r=>{const hit=norm(r.text).indexOf(q),start=Math.max(0,hit-50);return `<a href="#${r.href}" data-search-result><strong>${esc(r.title)}</strong><p>${start?'…':''}${esc(r.text.slice(start,start+180))}…</p></a>`}).join('')||'<p class="no-results">Chưa tìm thấy. Thử một từ khóa khác hoặc bỏ dấu tiếng Việt.</p>':'<p class="no-results">Nhập từ khóa để tìm trong cả hai lộ trình.</p>'}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.matches('[data-back]')){if(trail.length>1){trail.pop();backing=true;to(trail[trail.length-1])}}if(b.dataset.step)to('lesson/'+b.dataset.step);if(b.dataset.answer){const[t,id,n,i]=b.dataset.answer.split('|');answer(t,id,+n,+i)}if(b.dataset.retry){delete state.answers[b.dataset.retry];persist();render();$('.choice')?.focus({preventScroll:true})}if(b.dataset.complete){state.done[b.dataset.complete]=true;persist();render();toast('Đã ghi nhận. Bạn có thể ôn lại bất cứ lúc nào.')}if(b.dataset.jcomplete){const id=b.dataset.jcomplete;if(![0,1].every(i=>state.notes[id+'-'+i]?.trim())){toast('Hãy ghi một ý cho mỗi câu hỏi trước khi xác nhận.');return}state.done[id]=true;persist();render();toast('Đã ghi nhận suy ngẫm.')}if(b.hasAttribute('data-export'))exportNotes();if(b.hasAttribute('data-search-result'))$('#searchDialog').close()});
document.addEventListener('input',e=>{if(e.target.dataset.note){state.notes[e.target.dataset.note]=e.target.value;const j=e.target.dataset.note.match(/^(j[1-6])-/);if(j&&state.done[j[1]]){delete state.done[j[1]];const b=document.querySelector('[data-jcomplete]');if(b)b.textContent='Ghi nhận suy ngẫm'}persist()}});
$('#menuToggle').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open))});
main.addEventListener('click',()=>{if($('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false')}});
$('#searchOpen').addEventListener('click',()=>{$('#searchDialog').showModal();search();$('#searchInput').focus()});$('#searchInput').addEventListener('input',search);
window.addEventListener('hashchange',render);render();
// Retire previous offline cache on upgrade, preventing mixed v0.4/v0.5 resources.
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
